### ISSUE TITLE
newbie problem

### ISSUE THREAD

**Issue by skywaymsn** [AmadeusITGroup/NTP-Proxy#6]
After a git clone I'm getting
libnet.h: No such file or directory

I assume I'm missing an obvious dev library.  Any idea which?

\# repoquery --whatprovides '*libnet.h'|wc -l
0

OS: CentOS 6

**Comment by useidel** [comment]
Hi, you need a package called libnet-devel or similar. I don't have CentOS at hand to check for the exact name .. but libnet-devel must be very close.

**Comment by premkarat** [comment]
I hit the same issue while using this but overcame this issue by installing libnet from here.

http://liquidtelecom.dl.sourceforge.net/project/libnet-dev/libnet-1.1.6.tar.gz

./configure
make 
make install

and then

make ntpproxy

That should work

**Comment by skywaymsn** [comment]
Success@

**Comment by useidel** [comment]
Cool.
