### ISSUE TITLE
[RFE] Leap second insertion followed by leap second deletion within 10 seconds gap doesn't work 

### ISSUE THREAD

**Issue by premkarat** [AmadeusITGroup/NTP-Proxy#7]
Hi,
The following doesn't work,

1. Insert a leap second flag using sls.c (-d 10 -l add)
2. Wait for leap second to be inserted in kernel
3. After 10 seconds, check dmesg to see if leap second is inserted.
4. After confirming leap second is inserted, check for leap second deletion using (-d 10 -l del)
5. We can observer that leap second deletion doesn't happen.

Looks like the root cause for this issue is before we insert/delete leap second flag, time state needs to be cleared

```c
 // Set leap second flag 
    tx.modes=ADJ_STATUS;
    tx.status=ls;
    if(adjtimex(&tx) == -1) {
        perror("Error: STA_INS/STA_DEL not set");
        exit(1);
    }
  ```

I think a function like this would be better
```c
/* clear time state before calling insertion or deletion */
void clear_time_state(void) {
    struct timex tx;
    int ret;
    tx.modes = ADJ_STATUS;
    tx.status = STA_PLL;
    ret = adjtimex(&tx);

    tx.modes = ADJ_STATUS;
    tx.status = 0;
    ret = adjtimex(&tx);
}
 
 /* clear time state before setting flag */
    clear_time_state();
 // Set leap second flag 
    tx.modes=ADJ_STATUS;
    tx.status=ls;
    if(adjtimex(&tx) == -1) {
        perror("Error: STA_INS/STA_DEL not set");
        exit(1);
    }
```  

Note that, this is an excerpt from John Stultz leap second test.

**Comment by robertkarbowski** [comment]
Hello,
Thanks for suggestion.
I confirm kernel does not trigger other LS insertions/deletions if the flag is already set.
To be fixed as soon as I find a few free cycles ;).
Regards,
<robert>

**Comment by robertkarbowski** [comment]
Fixed in SLS ver. 1.3
